### ISSUE TITLE
It skips a lot

### ISSUE THREAD

**Issue by UpscaleAnon** [chupapee/telegram-stories-viewer-bot#1]
The bot only downloads first 4 stories, even if there's for example 43 or 91 active stories.
Would also be nice if it supplied a direct download link to the files, instead of reuploading jpeg files that will get compressed again.

**Comment by kamolmachine** [comment]
Unfortunately, there are some limitations preventing the download of all stories:
- The bot downloads all stories that can be obtained through the mtproto API, but it does not provide access to all of them
- The maximum limit for uploaded files is 50MB - files larger than this do not pass the filter (this can be resolved by setting up a local server as described here: https://core.telegram.org/bots/api#using-a-local-bot-api-server)
- Telegram does not provide direct links to stories, only metadata. Downloading occurs through passing this metadata to the mtproto API: https://painor.gitbook.io/gramjs/getting-started/available-methods/downloading-files. This issue can be addressed by downloading the stories and saving them in a database. However, since this requires significant resources, I didn't bother with it

**Comment by kamolmachine** [comment]
Issue was closed due to inactivity. If the issue persists or requires further attention, feel free to reopen it or create a new one. Thank you!
